#!/bin/bash
export DATABASE_URL="postgresql://postgres@localhost:5432/agency"
export EXCITED="true"
export FLASK_APP=app.py
export FLASK_DEBUG=true
export AUTH0_DOMAIN="thanhphamtrung.jp.auth0.com"
export ALGORITHMS=['RS256']
export API_AUDIENCE="agency"
export JWT=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ii1iNEx2bXNoaGJYOXllSDhOWFpPQSJ9.eyJpc3MiOiJodHRwczovL3RoYW5ocGhhbXRydW5nLmpwLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2NTE3ZWViOTkxMDFiZmNkYWVlZTQ5NGIiLCJhdWQiOiJhZ2VuY3kiLCJpYXQiOjE2OTYwNjc2NjIsImV4cCI6MTY5NjA3NDg2MiwiYXpwIjoiQVQxYWlXeUw5bmNNM2RINlZGdFZUbEpxV0NnSEVMOGsiLCJzY29wZSI6IiJ9.MvnVEw0k9UgXudg0o2cLKTxrHjDufktwnFqVBoX8JWvh_T1O2YkZ68DuzIMqWJPa5WwOZp48EDbe3TJosagzGnfmDq6AiXBRVFLicTYF27tddidEYiZNIhunqHuZYlK__WjxaIE8xirwxLvv1fdaHx_oKYH-x_cl-2RK6_Hp9M1NG8QXmaO80jvmnw_yjInfIEas47GGZXU2jNtBUqewMiRGSI1Oi7dwDR480FUNin4fLjdwIt8jbkA_GIAUcPNw6O1PFE5N5dmDB9drCjeOFu-AlYu0URk1AOEs6gfia7UJnw-tzFOr8qbAPsMXAIPlZ0l5Qmx4gRp1AvHYhRAYTg
echo "setup.sh script executed successfully!"
